# BitBucket Pipelines Configuration for Python Project
# This pipeline will run tests, build artifacts, and deploy on push/merge to main branch

image: python:3.9

definitions:
  steps:
    - step: &run-tests
        name: Run Python Tests
        script:
          # Set up virtual environment
          - python -m venv venv
          - source venv/bin/activate

          # Install dependencies
          - pip install --upgrade pip
          - pip install -r requirements.txt

          # Run linting
          - pip install flake8
          - flake8 .

          # Run unit tests
          - pip install pytest coverage
          - coverage run -m pytest
          - coverage report -m

          # Check test coverage (optional, adjust threshold as needed)
          - coverage report --fail-under=80




# Pipeline configurations
pipelines:
  # Trigger on all pushes to main branch
  branches:
    main:
      - parallel:
          # Run tests in parallel
          - step: *run-tests

          # Additional code quality checks can be added here
          - step:
              name: Security Scan
              script:
                - pip install safety
                - safety check

      - step:
          name: Build Deployment Package
          script:
            # Create distribution packages
            - pip install setuptools wheel
            - python setup.py sdist bdist_wheel

          artifacts:
            - dist/*

      - step:
          name: Deploy to Production
          deployment: production
          trigger: 'manual'
          script:
            # Example production deployment
            - echo 'Deployed'

  pull-requests:
    '**':
      - step: *run-tests